sonar.projectKey=verification-ios-sdk
sonar.projectName=verification-ios-sdk
sonar.projectVersion=3.3.0
sonar.host.url=http://localhost:9000

sonar.sources=Verification/Verification/Classes
sonar.tests=Verification/VerificationTests
sonar.sourceEncoding=UTF-8

sonar.inclusions=**/*.swift
sonar.test.inclusions=**/*Tests.swift,**/*Test.swift

sonar.exclusions=\
**/Pods/**,\
**/build/**,\
**/.swiftpm/**,\
**/.idea/**,\
**/docs/**,\
**/VerificationSample/**,\
**/Verification/VerificationTests/**

sonar.test.exclusions=\
**/Pods/**,\
**/build/**

sonar.scm.disabled=true
